In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))#type(): This built-in Python function tells us the type of the object passed to it. 
#To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#using tuple to create an array
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [19]:
#An array that has 1-D arrays as its elements is called a 2-D array.
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
import numpy as np
arr=([[1,2,3],[4,5,6]])
print(arr)

[[1, 2, 3], [4, 5, 6]]


In [20]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
import numpy as np
arr=[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
print(arr)

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]


In [21]:
#Check no of dimensions
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
import numpy as np
a=np.array(43)
b=np.array([1,2,3])#1 dimension array
c=np.array([[1,2,3],[4,5,6]])#2 dimension array
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])#3dimension array
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)





0
1
2
3


In [22]:
#When the array is created, you can define the number of dimensions by using the ndmin argument.
#High Dimensional array
#Create an array with 5 dimensions and verify that it has 5 dimensions:
import numpy as  np
arr=np.array([1,2,4,5] ,ndmin=10)
print(arr)
print("no of dimensions", arr.ndim)

[[[[[[[[[[1 2 4 5]]]]]]]]]]
no of dimensions 10


In [23]:
#Change data type from integer to boolean:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool
